package store

import (
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"testing"
)

func openTestDB(t *testing.T) *Paths {
	t.Helper()
	paths, err := Init(t.TempDir())
	if err != nil {
		t.Fatalf("Init: %v", err)
	}
	return &paths
}

// TestConcurrentWritesDoNotError below is the live guarantee for write
// correctness under contention (WAL + busy_timeout). A stricter
// SetMaxOpenConns(1) serialization was evaluated and rejected - it deadlocks
// the codebase's nested-cursor read loops; see the note in Open.

func TestEnsureSchemaIsIdempotent(t *testing.T) {
	paths := openTestDB(t)
	db, err := Open(*paths)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer db.Close()
	// Init already ran EnsureSchema once; running it again must not error.
	if err := EnsureSchema(db); err != nil {
		t.Fatalf("second EnsureSchema: %v", err)
	}
	var version int
	if err := db.QueryRow(`SELECT MAX(version) FROM schema_versions`).Scan(&version); err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if version != SchemaVersion {
		t.Fatalf("schema version = %d, want %d", version, SchemaVersion)
	}
}

func TestSignalsTableExists(t *testing.T) {
	paths := openTestDB(t)
	db, err := Open(*paths)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer db.Close()
	var name string
	err = db.QueryRow(`SELECT name FROM sqlite_master WHERE type='table' AND name='signals'`).Scan(&name)
	if err != nil {
		t.Fatalf("signals table not created: %v", err)
	}
}

func TestEvidenceQueryIndexesExist(t *testing.T) {
	paths := openTestDB(t)
	db, err := Open(*paths)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer db.Close()
	for _, index := range []string{
		"idx_events_run_time_id",
		"idx_events_run_type_time",
		"idx_events_run_tool_time",
		"idx_events_run_process_time",
		"idx_events_run_pid_time",
		"idx_graph_edges_run_from",
		"idx_graph_edges_run_to",
		"idx_risk_signals_run_event",
		"idx_policy_decisions_run_event",
	} {
		var name string
		if err := db.QueryRow(`SELECT name FROM sqlite_master WHERE type='index' AND name = ?`, index).Scan(&name); err != nil {
			t.Fatalf("index %s not created: %v", index, err)
		}
	}
}

// TestConcurrentWritesDoNotError exercises the single-connection write
// serialization: many goroutines inserting concurrently must all succeed
// rather than hitting "database is locked".
func TestConcurrentWritesDoNotError(t *testing.T) {
	paths := openTestDB(t)
	db, err := Open(*paths)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer db.Close()

	const writers = 16
	const perWriter = 25
	errs := make(chan error, writers)
	var wg sync.WaitGroup
	for w := 0; w < writers; w++ {
		wg.Add(1)
		go func(w int) {
			defer wg.Done()
			for i := 0; i < perWriter; i++ {
				id := fmt.Sprintf("lease-%d-%d", w, i)
				_, err := db.Exec(`INSERT INTO leases (id, run_id, task_path, task_yaml, status, created_at, updated_at)
					VALUES (?, ?, '', '', 'open', datetime('now'), datetime('now'))`, id, id)
				if err != nil {
					errs <- err
					return
				}
			}
		}(w)
	}
	wg.Wait()
	close(errs)
	for err := range errs {
		t.Fatalf("concurrent write failed: %v", err)
	}

	var count int
	if err := db.QueryRow(`SELECT COUNT(*) FROM leases`).Scan(&count); err != nil {
		t.Fatalf("count leases: %v", err)
	}
	if want := writers * perWriter; count != want {
		t.Fatalf("lease count = %d, want %d", count, want)
	}
}

func TestResolvePathsAbsolute(t *testing.T) {
	paths := ResolvePaths("relative/dir")
	if !filepath.IsAbs(paths.Root) {
		t.Fatalf("Root not absolute: %q", paths.Root)
	}
	if filepath.Base(paths.DB) != "agentprov.db" {
		t.Fatalf("DB path = %q, want .../agentprov.db", paths.DB)
	}
}

func TestUpgradeRealSchema15PreservesEventsAndFalcoSpool(t *testing.T) {
	// This fixture was generated by executing the actual schema statements
	// from commit 3093335, rather than simulating old state with today's schema.
	fixture, err := os.ReadFile(filepath.Join("testdata", "schema-v15.sql"))
	if err != nil {
		t.Fatal(err)
	}
	paths := ResolvePaths(t.TempDir())
	db, err := Open(paths)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if _, err := db.Exec(string(fixture)); err != nil {
		t.Fatal(err)
	}
	var before int
	if err := db.QueryRow(`SELECT MAX(version) FROM schema_versions`).Scan(&before); err != nil {
		t.Fatal(err)
	}
	if before != 15 {
		t.Fatalf("fixture version=%d", before)
	}
	for i := 0; i < 2; i++ {
		if err := EnsureSchema(db); err != nil {
			t.Fatalf("migration pass %d: %v", i, err)
		}
	}
	var version int
	if err := db.QueryRow(`SELECT MAX(version) FROM schema_versions`).Scan(&version); err != nil {
		t.Fatal(err)
	}
	if version != SchemaVersion {
		t.Fatalf("upgraded version=%d", version)
	}
	var payload, stamp string
	if err := db.QueryRow(`SELECT payload,created_at FROM events WHERE id='legacy-event'`).Scan(&payload, &stamp); err != nil {
		t.Fatal(err)
	}
	if payload != `{"path":"/legacy.env"}` || stamp != "2026-09-18T00:00:00.100Z" {
		t.Fatalf("legacy evidence changed: %q %q", payload, stamp)
	}
	var format, status, hash, options string
	var size, expires, retry, count, dropped int64
	if err := db.QueryRow(`SELECT format,status,file_sha256,size_bytes,native_options,expires_at,retry_at,event_count,dropped_count FROM telemetry_spool_batches WHERE id='legacy-falco'`).Scan(&format, &status, &hash, &size, &options, &expires, &retry, &count, &dropped); err != nil {
		t.Fatal(err)
	}
	if format != "falco" || status != "queued" || len(hash) != 64 || size != 22 || options != "{}" || expires != 0 || retry != 0 || count != 0 || dropped != 0 {
		t.Fatalf("legacy spool changed: %s %s %s %d %s %d %d %d %d", format, status, hash, size, options, expires, retry, count, dropped)
	}
	for _, table := range []string{"telemetry_native_rows", "telemetry_native_counters"} {
		var rows int
		if err := db.QueryRow(`SELECT COUNT(*) FROM ` + table).Scan(&rows); err != nil || rows != 0 {
			t.Fatalf("new table %s count=%d err=%v", table, rows, err)
		}
	}
	var index string
	if err := db.QueryRow(`SELECT name FROM sqlite_master WHERE type='index' AND name='idx_native_spool_ready'`).Scan(&index); err != nil {
		t.Fatal(err)
	}
}

func TestNewerSchemaIsRejectedBeforeMigrationWrites(t *testing.T) {
	paths := openTestDB(t)
	db, err := Open(*paths)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if _, err := db.Exec(`INSERT INTO schema_versions VALUES (?,'future','now')`, SchemaVersion+1); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`DROP TABLE telemetry_native_counters`); err != nil {
		t.Fatal(err)
	}
	if err := EnsureSchema(db); err == nil {
		t.Fatal("newer schema accepted")
	}
	var exists int
	if err := db.QueryRow(`SELECT COUNT(*) FROM sqlite_master WHERE name='telemetry_native_counters'`).Scan(&exists); err != nil {
		t.Fatal(err)
	}
	if exists != 0 {
		t.Fatal("old binary mutated newer schema")
	}
}
