// Run through playwright-cli run-code against TestContextDashboardFixture's
// actual local Dashboard. The fixture is synthetic, not a live-agent demo.
async (page) => {
  const checks = [], errors = [];
  const check = (condition, name) => { if (!condition) throw new Error(name); checks.push(name); };
  const settle = async () => { await page.waitForFunction(() => document.querySelector('#context-summary')?.textContent.includes('38')); };
  const readyBody = async (text) => { await page.waitForFunction(value => document.querySelector('#content-body')?.textContent.includes(value), text); };
  const records = () => page.locator('#context-body [data-entry]');
  const toolResult = () => records().filter({hasText:'Tool result'}).first();
  const base = await page.evaluate(() => location.origin);
  page = await page.context().newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({width:1440,height:1050});
  await page.goto(base+'/?run=ui-fixture&live=0&lang=en');
  await settle();
  await page.waitForFunction(()=>document.querySelector('#verify')?.textContent.includes('graph integrity'));
  check(!await page.locator('#context-fold').evaluate(el=>el.open),'session initially collapsed');
  check(await page.locator('#verify').innerText().then(text=>text.includes('graph integrity') && !text.includes('signed graph')),'graph verification not claimed as signature verification');
  for (const id of ['graphcard','siglist','focusedevidence','outboundcard','tl','ptree','egtbl','compliancecard']) check(await page.locator('#'+id).count()===1,'retains '+id);
  await page.getByRole('button',{name:'Agent session 38',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===30);
  check(await page.locator('#context-body img').count()===0,'recorded markup is not executed');
  await page.locator('#context-next').click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===10);
  check(await page.locator('#context-next').isDisabled(),'bounded entry pagination ends honestly');
  await page.locator('#context-prev').click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===30);
  await toolResult().locator('[data-tool-body] summary').click();
  await toolResult().getByText('SAVED-OUTPUT-START',{exact:false}).waitFor();
  await toolResult().getByRole('button',{name:'Open saved content',exact:true}).click();
  await readyBody('SAVED-OUTPUT-START');
  check(await page.locator('#content-body').innerText().then(text=>!text.includes('SAVED-OUTPUT-TAIL')),'first page is bounded at 64 KiB');
  await page.locator('#content-next').click();
  await readyBody('SAVED-OUTPUT-TAIL');
  check(await page.locator('#content-next').isDisabled(),'last saved output page is accessible');
  const tail = await page.locator('#content-body').innerText();
  await page.getByRole('button',{name:'Expand saved content',exact:true}).click();
  check(await page.locator('#content-dialog').evaluate(el=>el.open),'content expands independently');
  await page.getByRole('button',{name:'Close',exact:true}).click();
  check(await page.locator('#content-body').innerText()===tail,'close preserves content page');
  await page.locator('#content-choice').selectOption('1');
  await readyBody('"fixture":true');
  check(await page.locator('#content-body').innerText().then(text=>text.includes('tool_result')),'raw source record switch');
  await page.locator('#content-choice').selectOption('0');
  await readyBody('SAVED-OUTPUT-START');
  await toolResult().getByRole('button',{name:'Locate in graph',exact:true}).click();
  await page.locator('#detail-session').waitFor();
  check(await page.locator('#detail').innerText().then(text=>text.includes('python3 report.py') && text.includes('context-tool-')),'session follows exact recorded tool link');
  await page.locator('#detail-session').click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===2);
  check(await page.locator('#context-linked').isVisible(),'graph filters to the two linked input/result records');
  await page.locator('#context-return').click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===30);
  await records().first().getByRole('button',{name:'Locate in graph',exact:true}).click();
  await page.getByText('No recorded graph link.',{exact:false}).waitFor();
  check(true,'unlinked message is not guessed');
  await page.getByRole('tab',{name:'Permissions & configuration',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===2);
  await records().nth(0).getByRole('button',{name:'Compare snapshot',exact:true}).click();
  await records().nth(1).getByRole('button',{name:'Compare snapshot',exact:true}).click();
  await page.getByRole('button',{name:'Compare recorded values',exact:true}).click();
  await page.locator('#context-compare-result').getByText('/content/approval',{exact:true}).waitFor();
  check(await page.locator('#context-compare-result').innerText().then(text=>text.includes('Not recorded in this snapshot')),'missing approval remains unknown in comparison');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'output/playwright/context-desktop-en.png',fullPage:true});
  await page.getByRole('tab',{name:'Collection status',exact:true}).click();
  check(await page.locator('#context-body').innerText().then(text=>text.includes('Not recorded') && text.includes('synthetic-ui-fixture/v1')),'source coverage retains unknown counters and parser');
  await page.getByRole('tab',{name:'Conversation & tools',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===30);
  await toolResult().getByRole('button',{name:'Open saved content',exact:true}).click();
  await readyBody('SAVED-OUTPUT-START');
  await page.locator('#content-next').click();
  await readyBody('SAVED-OUTPUT-TAIL');
  await page.locator('#detail-content').click();
  await page.waitForFunction(()=>document.querySelector('#content-choice')?.selectedOptions[0]?.textContent==='Recorded graph content');
  check(true,'explicit graph content selection replaces the session preview');
  await toolResult().getByRole('button',{name:'Open saved content',exact:true}).click();
  await readyBody('SAVED-OUTPUT-START');
  await page.locator('#content-next').click();
  await readyBody('SAVED-OUTPUT-TAIL');
  await page.locator('#context-body').evaluate(el=>el.scrollTop=450);
  const scroll = await page.locator('#context-body').evaluate(el=>el.scrollTop);
  await page.locator('#live').click();
  await page.waitForTimeout(11000);
  check(await page.locator('#content-body').innerText()===tail,'live refresh preserves long-content page');
  check(await page.locator('#context-body').evaluate(el=>el.scrollTop)===scroll,'live refresh preserves session reading position');
  await page.locator('#live').click();
  await page.getByRole('link',{name:'中文',exact:true}).click();
  await settle();
  await readyBody('SAVED-OUTPUT-TAIL');
  check(await page.getByRole('tab',{name:'对话与工具',exact:true}).getAttribute('aria-selected')==='true','language switch preserves selected session tab');
  check(await page.locator('#context-body').evaluate(el=>Math.abs(el.scrollTop-450)<5),'language switch restores session reading position');
  check(await page.locator('#content-body').innerText()===tail,'language switch preserves original output and page');
  await page.locator('#savedcontent').scrollIntoViewIfNeeded();
  await page.screenshot({path:'output/playwright/context-desktop-zh.png'});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#agentcontext').scrollIntoViewIfNeeded();
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile has no page-wide overflow');
  await page.screenshot({path:'output/playwright/context-mobile-zh.png'});
  await page.getByRole('button',{name:'放大正文',exact:true}).click();
  check(await page.locator('#content-dialog').evaluate(el=>el.getBoundingClientRect().width<=innerWidth),'mobile dialog fits viewport');
  check(await page.locator('#content-next').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight && el.getBoundingClientRect().top>=0),'mobile dialog pagination stays visible');
  await page.screenshot({path:'output/playwright/context-mobile-content.png'});
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.route('**/api/context/entries?*', route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":{"message":"test unavailable"}}'}));
  await page.getByRole('button',{name:'刷新已保存记录',exact:true}).click();
  await page.locator('#context-body [role=alert]').waitFor();
  check(true,'entry API failure is visible, not rendered as empty success');
  await page.unroute('**/api/context/entries?*');
  await page.getByRole('button',{name:'刷新已保存记录',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===30);
  check(errors.length===0,'no unhandled browser errors: '+errors.join('; '));
  return {fixture:'synthetic, not a live capture',checks:checks.length,passed:checks,screenshots:'output/playwright/context-*.png'};
}
