// Run through playwright-cli run-code against TestContextDashboardFixture's
// actual local Dashboard. The fixture is synthetic, not a live-agent demo.
async (page) => {
  const checks = [], errors = [];
  const check = (condition, name) => { if (!condition) throw new Error(name); checks.push(name); };
  const settle = async () => { await page.waitForFunction(() => document.querySelector('#context-summary')?.textContent.includes('38')); };
  const readyBody = async (text) => { await page.waitForFunction(value => document.querySelector('#content-body')?.textContent.includes(value), text); };
  const records = () => page.locator('#context-body [data-entry]');
  const toolResult = () => records().filter({hasText:'Tool result'}).first();
  const base = await page.evaluate(() => location.origin);
  page = await page.context().newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({width:1440,height:1050});
  await page.goto(base+'/?run=ui-fixture&live=0&lang=en');
  await settle();
  await page.waitForFunction(()=>document.querySelector('#verify')?.textContent.includes('graph integrity'));
  check(!await page.locator('#context-fold').evaluate(el=>el.open),'session initially collapsed');
  check(await page.locator('#context-summary').innerText().then(text=>text.includes('Includes prior context')),'summary distinguishes retained historical records');
  check(await page.locator('#context-summary').innerText().then(text=>text.includes('38 message records')),'summary counts source records, not inferred unique messages');
  check(await page.locator('#verify').innerText().then(text=>text.includes('graph integrity') && !text.includes('signed graph')),'graph verification not claimed as signature verification');
  for (const id of ['graphcard','siglist','focusedevidence','outboundcard','tl','ptree','egtbl','compliancecard']) check(await page.locator('#'+id).count()===1,'retains '+id);
  check(await page.locator('#runoverview .context-nav button').count()===5,'overview retains task, tool, file, configuration and coverage shortcuts');
  await page.getByRole('button',{name:'File evidence',exact:true}).click();
  await page.waitForFunction(()=>Math.abs(document.querySelector('#savedcontent').getBoundingClientRect().top-document.querySelector('body > header').getBoundingClientRect().bottom-12)<5);
  check(!await page.locator('#context-fold').evaluate(el=>el.open),'file shortcut opens independent preview without expanding session');
  await page.getByRole('button',{name:'Permissions & configuration 2',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#context-tab-configuration')?.getAttribute('aria-selected')==='true');
  check(await page.locator('#context-fold').evaluate(el=>el.open),'configuration shortcut expands its matching tab');
  await page.locator('[data-context-open="coverage"]').click();
  await page.waitForSelector('[data-runtime-coverage]');
  check(await page.locator('#context-tab-coverage').getAttribute('aria-selected')==='true','coverage shortcut opens the report');
  await page.getByRole('button',{name:'Tool calls 1',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#context-tab-conversation')?.getAttribute('aria-selected')==='true');
  check(true,'tool shortcut opens conversation and tool records');
  await page.getByRole('button',{name:'Task & conversation 38',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===30);
  await page.waitForFunction(()=>document.querySelector('#agentcontext').getBoundingClientRect().top >= document.querySelector('body > header').getBoundingClientRect().bottom);
  check(true,'session navigation clears the sticky header');
  check(await page.locator('#context-body img').count()===0,'recorded markup is not executed');
  check(await page.locator('#context-body .context-status').allTextContents().then(values=>values.includes('Source message event')),'event-only message representation is labeled');
  check(await records().first().locator('.context-meta').innerText().then(text=>text.includes('Prior context')),'history is visibly scoped');
  check(await toolResult().locator('.context-meta').innerText().then(text=>text.includes('Current execution range')),'new result is visibly scoped');
  await page.locator('#context-next').click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===10);
  check(await page.locator('#context-next').isDisabled(),'bounded entry pagination ends honestly');
  await page.locator('#context-prev').click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===30);
  await toolResult().locator('[data-tool-body] summary').click();
  await toolResult().getByText('SAVED-OUTPUT-START',{exact:false}).waitFor();
  await toolResult().getByRole('button',{name:'Open saved content',exact:true}).click();
  await readyBody('SAVED-OUTPUT-START');
  check(await page.locator('#content-body').innerText().then(text=>!text.includes('SAVED-OUTPUT-TAIL')),'first page is bounded at 64 KiB');
  await page.locator('#content-next').click();
  await readyBody('SAVED-OUTPUT-TAIL');
  check(await page.locator('#content-next').isDisabled(),'last saved output page is accessible');
  const tail = await page.locator('#content-body').innerText();
  await page.getByRole('button',{name:'Expand saved content',exact:true}).click();
  check(await page.locator('#content-dialog').evaluate(el=>el.open),'content expands independently');
  await page.getByRole('button',{name:'Close',exact:true}).click();
  check(await page.locator('#content-body').innerText()===tail,'close preserves content page');
  await page.locator('#content-choice').selectOption('1');
  await readyBody('"fixture":true');
  check(await page.locator('#content-body').innerText().then(text=>text.includes('tool_result')),'raw source record switch');
  await page.locator('#content-choice').selectOption('0');
  await readyBody('SAVED-OUTPUT-START');
  await toolResult().getByRole('button',{name:'Locate in graph',exact:true}).click();
  await page.locator('#detail-session').waitFor();
  check(await page.locator('#detail').innerText().then(text=>text.includes('python3 report.py') && text.includes('context-tool-')),'session follows exact recorded tool link');
  await page.locator('#detail-session').click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===2);
  check(await page.locator('#context-linked').isVisible(),'graph filters to the two linked input/result records');
  await page.locator('#context-return').click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===30);
  await records().first().getByRole('button',{name:'Locate in graph',exact:true}).click();
  await page.getByText('This is prior context, not activity in the current execution.',{exact:false}).waitFor();
  check(true,'historical message cannot navigate to current execution');
  await page.getByRole('tab',{name:'Permissions & configuration',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===2);
  check(await records().first().locator('.context-status').innerText()==='Session metadata','configuration event has a readable label');
  await records().nth(0).getByRole('button',{name:'Compare snapshot',exact:true}).click();
  await records().nth(1).getByRole('button',{name:'Compare snapshot',exact:true}).click();
  await page.getByRole('button',{name:'Compare recorded values',exact:true}).click();
  await page.locator('#context-compare-result').getByText('/content/approval',{exact:true}).waitFor();
  check(await page.locator('#context-compare-result').innerText().then(text=>text.includes('Not recorded in this snapshot')),'missing approval remains unknown in comparison');
  const pluginChange = page.locator('.context-change').filter({has:page.getByText('/content/plugins',{exact:true})});
  check(await pluginChange.innerText().then(text=>text.includes('null') && text.includes('Not recorded in this snapshot')),'explicit null differs from absent configuration');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'output/playwright/context-desktop-en.png',fullPage:true});
  await page.getByRole('tab',{name:'Collection status',exact:true}).click();
  check(await page.locator('[data-runtime-coverage]').innerText().then(text=>text.includes('Not recorded in this historical run') && text.includes('Stored runtime events') && !text.includes('Run-specific dropped events')),'historical capture is unknown without a fictitious run-loss count');
  await page.locator('[data-source-diagnostics] > summary').first().click();
  check(await page.locator('#context-body').innerText().then(text=>text.includes('Not recorded') && text.includes('synthetic-ui-fixture/v1')),'source coverage retains unknown counters and parser');
  check(await page.locator('#context-body').innerText().then(text=>text.includes('Approval decision') && text.includes('MCP servers') && text.includes('Network restrictions')),'configuration field gaps use readable names');
  check(await page.locator('#context-body').innerText().then(text=>text.includes('Completeness of configuration change history') && text.includes('completeness of the change history is unknown.')),'recorded configuration changes do not imply complete history');
  await page.locator('#context-body summary').filter({hasText:'Prior context'}).click();
  check(await page.locator('#context-body').innerText().then(text=>text.includes('Historical approvals do not authorize new actions.')),'historical coverage and authorization boundaries are explicit');
  await page.getByRole('tab',{name:'Conversation & tools',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===30);
  await toolResult().getByRole('button',{name:'Open saved content',exact:true}).click();
  await readyBody('SAVED-OUTPUT-START');
  await page.locator('#content-next').click();
  await readyBody('SAVED-OUTPUT-TAIL');
  await page.locator('#detail-content').click();
  await page.waitForFunction(()=>document.querySelector('#content-choice')?.selectedOptions[0]?.textContent==='Recorded graph content');
  check(true,'explicit graph content selection replaces the session preview');
  await toolResult().getByRole('button',{name:'Open saved content',exact:true}).click();
  await readyBody('SAVED-OUTPUT-START');
  await page.locator('#content-next').click();
  await readyBody('SAVED-OUTPUT-TAIL');
  await page.locator('#context-body').evaluate(el=>el.scrollTop=450);
  const scroll = await page.locator('#context-body').evaluate(el=>el.scrollTop);
  await page.locator('#live').click();
  await page.waitForTimeout(11000);
  check(await page.locator('#content-body').innerText()===tail,'live refresh preserves long-content page');
  check(await page.locator('#context-body').evaluate(el=>el.scrollTop)===scroll,'live refresh preserves session reading position');
  await page.locator('#live').click();
  await page.getByRole('link',{name:'中文',exact:true}).click();
  await settle();
  await readyBody('SAVED-OUTPUT-TAIL');
  check(await page.getByRole('tab',{name:'对话与工具',exact:true}).getAttribute('aria-selected')==='true','language switch preserves selected session tab');
  check(await page.locator('#context-body').evaluate(el=>Math.abs(el.scrollTop-450)<5),'language switch restores session reading position');
  check(await page.locator('#content-body').innerText()===tail,'language switch preserves original output and page');
  check(await records().first().locator('.context-meta').innerText().then(text=>text.includes('历史上下文')),'historical boundary is localized');
  check(await page.locator('#context-body .context-status').allTextContents().then(values=>values.includes('来源消息事件')),'source message event label is localized');
  await page.locator('#savedcontent').scrollIntoViewIfNeeded();
  await page.screenshot({path:'output/playwright/context-desktop-zh.png'});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#agentcontext').scrollIntoViewIfNeeded();
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile has no page-wide overflow');
  await page.screenshot({path:'output/playwright/context-mobile-zh.png'});
  await page.getByRole('button',{name:'放大正文',exact:true}).click();
  check(await page.locator('#content-dialog').evaluate(el=>el.getBoundingClientRect().width<=innerWidth),'mobile dialog fits viewport');
  check(await page.locator('#content-next').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight && el.getBoundingClientRect().top>=0),'mobile dialog pagination stays visible');
  await page.screenshot({path:'output/playwright/context-mobile-content.png'});
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.route('**/api/context/entries?*', route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":{"message":"test unavailable"}}'}));
  await page.getByRole('button',{name:'刷新已保存记录',exact:true}).click();
  await page.locator('#context-body [role=alert]').waitFor();
  check(true,'entry API failure is visible, not rendered as empty success');
  await page.unroute('**/api/context/entries?*');
  await page.getByRole('button',{name:'刷新已保存记录',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===30);
  await page.setViewportSize({width:1440,height:1050});
  await page.goto(base+'/?run=ui-deepseek-protocol&live=0&lang=en');
  await page.waitForFunction(()=>document.querySelector('#context-summary')?.textContent.includes('3 tool calls'));
  await page.getByRole('button',{name:'Task & conversation 1',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===7);
  const protocolStatuses = await page.locator('#context-body .context-status').allTextContents();
  for (const label of ['Model-proposed tool','Completion recorded; start not recorded','Replaced context; not a new execution']) check(protocolStatuses.includes(label),'DeepSeek representation: '+label);
  const completedOnly = records().filter({hasText:'Completion recorded; start not recorded'});
  await completedOnly.getByRole('button',{name:'Locate in graph',exact:true}).click();
  await page.waitForFunction(()=>[...document.querySelectorAll('.context-link-result')].some(el=>el.textContent.includes('No recorded graph link')));
  check(true,'completion-only sub-call has no invented runtime association');
  const subcallResult = records().filter({has:page.locator('.context-status').filter({hasText:/^error$/})});
  await subcallResult.getByRole('button',{name:'Raw source record',exact:true}).click();
  await readyBody('parentCallId');
  check(await page.locator('#content-body').innerText().then(text=>text.includes('rootCallId') && text.includes('isError')),'PTC raw parent identity and structured error preserved');
  const replacement = records().filter({hasText:'Replaced context; not a new execution'});
  await replacement.getByRole('button',{name:'Raw source record',exact:true}).click();
  await readyBody('sourceEventSeqs');
  check(await page.locator('#content-body').innerText().then(text=>text.includes('surfaceOp')),'replacement retains compaction source references');
  await page.getByRole('link',{name:'中文',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===7);
  const translated = await page.locator('#context-body .context-status').allTextContents();
  for (const label of ['模型提出的工具调用','已记录完成结果；未记录开始时间','上下文替换；不是新执行']) check(translated.includes(label),'DeepSeek localized representation: '+label);
  await page.locator('#agentcontext').scrollIntoViewIfNeeded();
  await page.screenshot({path:'output/playwright/context-deepseek-protocol-zh.png'});
  await page.goto(base+'/?run=ui-claude-compound&live=0&lang=en');
  await page.waitForFunction(()=>document.querySelector('#context-summary')?.textContent.includes('2 message records'));
  await page.getByRole('button',{name:'Task & conversation 2',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#context-body [data-entry]').length===2 && document.querySelector('#context-body')?.textContent.includes('COMPOUND-SECOND'));
  check(await records().first().innerText().then(text=>text.includes('COMPOUND-FIRST') && text.includes('#1.1')),'same-line first message keeps its physical position');
  check(await records().nth(1).innerText().then(text=>text.includes('COMPOUND-SECOND') && text.includes('#1.2')),'same-line second message is displayed after the first');

  // Explicitly synthetic response variants exercise rare coverage states;
  // live-demo checks use the separate unmodified signed-capture script.
  const baseline = await (await page.request.get(base+'/api/context/overview?run=ui-fixture')).json();
  let mocked;
  await page.route('**/api/context/overview?*', route=>route.fulfill({json:mocked}));
  for (const lang of ['en','zh-CN']) {
    for (const variant of [
      {status:'partial',lost:null,label:['Capture completeness unconfirmed','采集完整性待确认'],badge:'partial'},
      {status:'ok',lost:2,label:['Run event loss confirmed','已确认本次事件丢失'],badge:'failed'},
      {status:'disabled',lost:null,label:['Not enabled','未启用'],badge:'disabled'},
    ]) {
      mocked = JSON.parse(JSON.stringify(baseline));
      Object.assign(mocked.runtime_coverage.capture,{status:variant.status,run_dropped_events:variant.lost,node_pending_events:235});
      await page.goto(base+'/?run=ui-fixture&live=0&lang='+lang);
      await settle();
      await page.locator('[data-context-open="coverage"]').click();
      const coverage = page.locator('[data-runtime-coverage]');
      check((await coverage.innerText()).includes(variant.label[lang==='en'?0:1]),lang+': synthetic '+variant.status+' label');
      check(await coverage.locator('.context-status').getAttribute('data-status')===variant.badge,lang+': synthetic '+variant.status+' severity');
      check(!(await coverage.innerText()).includes('235'),lang+': node backlog stays diagnostic');
      if (variant.lost) check((await coverage.locator('.context-counts').innerText()).includes('2'),lang+': confirmed run loss stays prominent');
    }
  }
  await page.unroute('**/api/context/overview?*');
  check(errors.length===0,'no unhandled browser errors: '+errors.join('; '));
  return {fixture:'synthetic, not a live capture',checks:checks.length,passed:checks,screenshots:'output/playwright/context-*.png'};
}
